### ISSUE TITLE
По поводу IE...

### ISSUE THREAD

**Issue by SelenIT** [kizu/kizu.ru#171]
Забавно, что как раз в IE еще при царе Горохе была техническая возможность вкладывать ссылку в ссылку — правда, с оберткой не в виде `object`, а в виде таблицы. Этим, в частности, пользовался Стю Николз в [одной из версий своего CSS-меню](http://www.cssplay.co.uk/menus/dd_valid_2.html). Судя по всему, это работает и в IE8 (при наведении на внешнюю ссылку внутренняя подсвечивается, но ведет куда надо), так что можно совместить:)

Но всё-таки я считаю запрет на вкладывание интерактивных элементов друг в друга разумным ограничением, помогающим миллионам новичков лучше понять собственную задачу. По моим наблюдениям, задача со вложенными ссылками чаще всего возникает по недоразумению. А те, кто приходят к такой задаче осознанно, как правило, владеют более продвинутыми средствами ее решения, чем HTML.

**Comment by kizu** [comment]
Вариант с таблицей забавный, да. У меня ещё идея попробовать через экспрешны динамически всякое вставлять — может прокатить, но влом этим заниматься, так как на наших проектах мы ие9- уже не поддерживаем.

Что касается запрета — я не согласен. Нельзя решать проблемы новичков, запрещая вообще всем что-либо. Это тупиковый путь. Не говоря уж о том, что само наличие этих проблем — не объективно.
