### ISSUE TITLE
О переносах.

### ISSUE THREAD

**Issue by exdeniz** [kizu/kizu.ru#184]
Привет Роман. Я в свое время экспериментировал с переносами. Конечно стандартными средствами веба они совершенно не годятся. Я делал по мотивам этого видео https://vimeo.com/82527410 
Расскажи о своем опыте пожалуйста.

PS hayaka так и не будет портирована на JS? (очень хочется ее для atom)

**Comment by kizu** [comment]
Я сейчас использую hypher. Видео посмотрю чуть позже, наверняка у меня не идеальное решение, может получится что-то оттуда адаптировать тоже, спасибо :)

**Comment by kizu** [comment]
(в итоге оставил вариант на CSS hyphens)
