### ISSUE TITLE
Feedback for “Nested Links”

### ISSUE THREAD

**Issue by tigt** [kizu/kizu.ru#197]
There is one way where [nested links are standards-compliant as of today](https://validator.nu/?doc=data%3Atext%2Fhtml%3Bcharset%3Dutf-8%2C%253C%2521DOCTYPE%2520html%253E%250D%250A%253Ctitle%253ETest%253C%252Ftitle%253E%250D%250A%250D%250A%253Csvg%253E%250D%250A%2520%2520%253Ctext%2520y%253D%25221em%2522%253E%250D%250A%2520%2520%2520%2520%253Ca%2520xlink%253Ahref%253D%2522%2523fee%2522%253Efi%250D%250A%2520%2520%2520%2520%2520%2520%253Ca%2520xlink%253Ahref%253D%2522%2523fo%2522%253Efum%253C%252Fa%253E%250D%250A%2520%2520%2520%2520%253C%252Fa%253E%250D%250A%2520%2520%253C%252Ftext%253E%250D%250A%253C%252Fsvg%253E&showsource=yes): SVG (and ergo inline SVG) has always allowed them:

```html
<svg>
  <text y="1em">
    <a xlink:href="#fee">fi
      <a xlink:href="#fo">fum</a>
    </a>
  </text>
</svg>
```

This isn’t perfect for all use-cases, but I thought it might be of interest to you.

**Comment by kizu** [comment]
Oh, nice! Thanks for the find!
